-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 22:05:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema terminapp_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema terminapp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `terminapp_db` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `terminapp_db` ;

-- -----------------------------------------------------
-- Table `terminapp_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`terminales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`terminales` (
  `terminal_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `num_direccion` INT NOT NULL,
  `comuna` VARCHAR(45) NOT NULL,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  PRIMARY KEY (`terminal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`empresas` (
  `empresa_id` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `razon_social` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`empresa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`recorridos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`recorridos` (
  `recorrido_id` INT NOT NULL AUTO_INCREMENT,
  `origen` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `tarifa_adulto` INT NOT NULL,
  `tarifa_estudiante` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`recorrido_id`),
  INDEX `fk_recorridos_empresas1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_recorridos_empresas1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `terminapp_db`.`empresas` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`horarios` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `hora_salida` TIME(5) NOT NULL,
  `hora_llegada` TIME(5) NOT NULL,
  `recorrido_id` INT NOT NULL,
  PRIMARY KEY (`horario_id`),
  INDEX `fk_horarios_recorridos1_idx` (`recorrido_id` ASC),
  CONSTRAINT `fk_horarios_recorridos1`
    FOREIGN KEY (`recorrido_id`)
    REFERENCES `terminapp_db`.`recorridos` (`recorrido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`Terminal_has_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`Terminal_has_Empresa` (
  `Terminal_id` INT NOT NULL,
  `Empresa_id` INT NOT NULL,
  PRIMARY KEY (`Terminal_id`, `Empresa_id`),
  INDEX `fk_Terminal_has_Empresa_Empresa1_idx` (`Empresa_id` ASC),
  INDEX `fk_Terminal_has_Empresa_Terminal_idx` (`Terminal_id` ASC),
  CONSTRAINT `fk_Terminal_has_Empresa_Terminal`
    FOREIGN KEY (`Terminal_id`)
    REFERENCES `terminapp_db`.`terminales` (`terminal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terminal_has_Empresa_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `terminapp_db`.`empresas` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`terminales_has_terminales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`terminales_has_terminales` (
  `terminales_id` INT NOT NULL,
  `terminales_id1` INT NOT NULL,
  PRIMARY KEY (`terminales_id`, `terminales_id1`),
  INDEX `fk_terminales_has_terminales_terminales2_idx` (`terminales_id1` ASC),
  INDEX `fk_terminales_has_terminales_terminales1_idx` (`terminales_id` ASC),
  CONSTRAINT `fk_terminales_has_terminales_terminales1`
    FOREIGN KEY (`terminales_id`)
    REFERENCES `terminapp_db`.`terminales` (`terminal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_terminales_has_terminales_terminales2`
    FOREIGN KEY (`terminales_id1`)
    REFERENCES `terminapp_db`.`terminales` (`terminal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`terminales_has_empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`terminales_has_empresas` (
  `terminales_id` INT NOT NULL,
  `empresas_id` INT NOT NULL,
  PRIMARY KEY (`terminales_id`, `empresas_id`),
  INDEX `fk_terminales_has_empresas1_empresas1_idx` (`empresas_id` ASC),
  INDEX `fk_terminales_has_empresas1_terminales1_idx` (`terminales_id` ASC),
  CONSTRAINT `fk_terminales_has_empresas1_terminales1`
    FOREIGN KEY (`terminales_id`)
    REFERENCES `terminapp_db`.`terminales` (`terminal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_terminales_has_empresas1_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `terminapp_db`.`empresas` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`terminales_empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`terminales_empresas` (
  `terminal_empresa_id` INT NULL AUTO_INCREMENT,
  `terminal_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`terminal_empresa_id`),
  INDEX `fk_terminales_has_empresas1_empresas2_idx` (`empresa_id` ASC),
  INDEX `fk_terminales_has_empresas1_terminales2_idx` (`terminal_id` ASC),
  CONSTRAINT `fk_terminales_has_empresas1_terminales2`
    FOREIGN KEY (`terminal_id`)
    REFERENCES `terminapp_db`.`terminales` (`terminal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_terminales_has_empresas1_empresas2`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `terminapp_db`.`empresas` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`comentarios` (
  `comentario_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  `usuario_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`comentario_id`),
  INDEX `fk_usuarios_has_empresas_empresas1_idx` (`empresa_id` ASC),
  INDEX `fk_usuarios_has_empresas_usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuarios_has_empresas_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `terminapp_db`.`usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_empresas_empresas1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `terminapp_db`.`empresas` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminapp_db`.`calificaciones_empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `terminapp_db`.`calificaciones_empresas` (
  `calificacion_id` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  INDEX `fk_usuarios_has_empresas_empresas2_idx` (`empresa_id` ASC),
  INDEX `fk_usuarios_has_empresas_usuarios2_idx` (`usuario_id` ASC),
  PRIMARY KEY (`calificacion_id`),
  CONSTRAINT `fk_usuarios_has_empresas_usuarios2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `terminapp_db`.`usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_empresas_empresas2`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `terminapp_db`.`empresas` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
